### ISSUE TITLE
UI changes for WWW

### ISSUE THREAD

**Issue by rakeshr1** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-android#38]
1. Disable auto-complete in the textbox
2. Provide 3 buttons for confirming: YES, NO, TRAIN
3. Remove suggestion bar. Suggestion: Bubble conversations
4. Always confirm even for query and monitor before doing any slot filling
5. Change make rule flow. Have 3 buttons for WHEN, GET, DO and use a separate view to fill them

**Comment by gcampax** [comment]
Are we still doing any of this?

**Comment by gcampax** [comment]
Probably not.
